server:
  port: 8081


spring:
# astra
  data:
    cassandra:
      keyspace-name: main
      username: AUnGhASGJxQtFmnBbsPwOIRt
      password: cpNPRh7eZ0,QQkd02rHMiSNEZUZ414PKMZIzOY1bqJsqFnaRx,tmmO1,mLt2wmTEMfQkJOzfQ4SZI2QYZcDKDT1Ih28l8nOofAvwaExtEtpIGOZvsqvNR2rKApPTHImO
      schema-action: create_if_not_exists
      request:
        timeout: 20s
      connection:
        connect-timout: 20s
        init-query-timeout: 20s

# oauth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.c10e0896c081f87c
            client-secret: 46a1d2a8d6520d50d7e45390606dc774c996d84d


datastax.astra:
  secure-connect-bundle: secure-connect-tinhong2.zip
astra.db:
  id: b5c6e810-0fc9-4de4-b0bd-40541515e237-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:AUnGhASGJxQtFmnBbsPwOIRt:9805bff2ec547a307751eb34bc3c0e181b1fff1044b5822e5ffaae349359bcad


# application
tinhong:
  secret-key: colammoicoan

# oauth2
security:
  oauth2:
    resource:
      filter-order: 3

access:
  key:
    id: AKIATK7H6PFSRDBRS3ZA
    secret: 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

s3:
  region:
    name: ap-southeast-1
  bucket:
    name: tinhong



