server:
  port: 8081


spring:
# astra
  data:
    cassandra:
      keyspace-name: main
      username: PQYYISzxwEgwRrftkUKXKNGv
      password: CC_67i_q2u6Fq45SHJYvr0uTbokhosF3TkZbzZHJ4Eln1AA4RfvsG8Re.zm8gtPf,L,K3HKxvNjMUb_uaylMZWHWZ-dxvfDUcDB1CdiSQc-vMqIlUp_MvR6JOOjbhytg
      schema-action: recreate_drop_unused
      request:
        timeout: 20s
      connection:
        connect-timout: 20s
        init-query-timeout: 20s

# oauth2
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.c10e0896c081f87c
            client-secret: 46a1d2a8d6520d50d7e45390606dc774c996d84d


datastax.astra:
  secure-connect-bundle: secure-connect-tinhong.zip
astra.db:
  id: b5c6e810-0fc9-4de4-b0bd-40541515e237-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:PQYYISzxwEgwRrftkUKXKNGv:b744c2f301884cd2aa5b940f5869efce7c8c1b29b2d8090448ccdaa8d8c512b3


# application
tinhong:
  secret-key: colammoicoan



